function inspToolbar(fig) 
% *************************** Setup frame and pushbuttons ******************************
% Create the background Toolbar
  global BlackBoard
  global Ntraces
  
  toolbar_position   = [ 0.050 0.85  0.70   0.12 ];
  button_position    = [ 0.050 0.050 1/9.5  0.3 ];
  button_color       = [0.701961 0.701961 0.701961];
  button_left_shift  = button_position(3) * 1.10;
  
  b = uipanel('Parent',           fig, ...
              'Units',           'Normalized', ...
              'BackgroundColor',  [0.5 0.5 0.8], ...
              'Position',         toolbar_position, ...
              'Tag',             'ToolBar');
  
  % Time Struct Button
  
  B = struct ( 'string', ...
               {'Times struct', 'Station struct', 'Event struct', ...
                'User struct',  'Descrip struct', 'Evsta struct', ...
                'LLNL struct', 'Response Struct'}, ...
               'tag', ...
               {'Times', 'Station', 'Event', 'User', 'Descrip', 'Evsta', 'llnl', 'response' }, ...
               'callback', ...
               { 'inspCallbacks(''time'')',     ...
                 'inspCallbacks(''stat'')',     ...
                 'inspCallbacks(''event'')',    ...
                 'inspCallbacks(''user'')',     ...               
                 'inspCallbacks(''descrip'')',  ...               
                 'inspCallbacks(''evsta'')',    ...               
                 'inspCallbacks(''llnl'')',     ...               
                 'inspCallbacks(''response'')', ...               
               });
  
  for i = 1:length(B)
    c = uicontrol('Parent',          b, ...
                  'Units',          'Normalized', ...
                  'BackgroundColor', button_color, ...
                  'Position',        button_position, ...
                  'String',          B(i).string, ...
                  'Callback',        B(i).callback, ...
                  'Tag',             B(i).tag);
    button_position(1) = button_position(1) + button_left_shift;
  end
  if ~isempty(BlackBoard)	
    b = uicontrol('Parent',      a, ...
                  'Units',              'Normalized', ...
                  'BackgroundColor',     button_color, ...
                  'Position',            button_position, ...
                  'String',             'Blackboard struct', ...
                  'Callback',           'inspCallbacks(''bboard'')', ...
                  'Tag',                'BlackBoard');
  end	
  
  
  button_quit_position = [ 0.05 0.55 1/3.5 0.3 ];
  button_quit_color    = [0.901961 0.701961 0.7];
  
  c = uicontrol('Parent',    b, ...
                'Units',          'Normalized', ...
                'Position',        button_quit_position, ...
                'BackgroundColor', button_quit_color, ...
                'String',         'Quit', ...
                'Callback',       'close', ...
                'Tag','close');
  
  button_quit_position(1) = button_quit_position(1) + button_quit_position(3) * 1.10;
  c = uicontrol('Parent',       b, ...
                'Units',       'Normalized', ...
                'Position',     button_quit_position, ...
                'String',      'Previous Trace', ...
                'Callback',    'inspCallbacks(''prev'')', ...
                'Enable',      'off', ...
                'Tag',         'Previous');
  button_quit_position(1) = button_quit_position(1) + button_quit_position(3) * 1.10;
  
  enable_button = 'off';
  if(Ntraces > 1) 
    enable_button = 'on';
  end
  c = uicontrol('Parent',       b, ...
                'Units',       'Normalized', ...
                'Position',     button_quit_position, ...
                'String',      'Next Trace', ...
                'Callback',    'inspCallbacks(''next'')', ...
                'Enable',      enable_button , ...
                'Tag',         'Next');
  
