function [fig, ax] = inspFigure()
  
% Get the screen Size
  screen = get(0,'ScreenSize'); 
  
  % Set the Width and Height of the Window
  width  = 960;
  height = 625;
  % Set the Bottom, Left Corner of the Window
  left   = (screen(3) - width)/2;
  bot    = (screen(4) - height)/2;
  
  % Create the Figure
  fig = figure('Color',[0.8 0.8 0.8], ...
               'Name','SAC data Inspector', ...
               'NumberTitle','off', ...
               'MenuBar','none', ...
               'Position',[left, bot, width, height], ...
               'WindowButtonUpFcn','inspCallbacks(''Delete'')', ...
               'Tag','Fig1');
  
  % Setup the Axes the of Figure
  ax = axes('Parent',fig, ...
            'Box','on', ...
            'CameraUpVector',[0 1 0], ...
            'Color',[1 1 1], ...
            'Position',[0.0994695 0.101449 0.803714 0.695652], ...
            'Tag','Axes1', ...
            'XColor',[0 0 0], ...
            'YColor',[0 0 0], ...
            'ZColor',[0 0 0]);
